version: "3.8"
services:
  db:
    image: postgres:13.7
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=comfort
      - PGDATA=/var/lib/postgresql/data
    ports:
      - "5433:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - ./src/main/resources/sql:/scripts
    networks:
      - comfort-network

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d comfort -p 5432" ]
      interval: 5s
      timeout: 5s
      retries: 3

  app:
    build: .
    restart: always
    container_name: app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/comfort
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"
    networks:
      - comfort-network
    depends_on:
      db:
        condition: service_healthy

  nginx:
    image: nginx:1.22.0-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - comfort-network
    links:
      - app
volumes:
  db-data:

networks:
  comfort-network:
    driver: bridge
