version: "3.8"
services:
  db:
    image: postgres:13.7
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=comfort
      - PGDATA=/var/lib/postgresql/data
    ports:
      - "5433:5432"
    volumes:
      - ./pg_data_v2:/var/lib/postgresql/data
      - ./src/main/resources/sql:/scripts
    networks:
      - comfort-network

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d comfort -p 5432" ]
      interval: 5s
      timeout: 5s
      retries: 3

  app:
    build: .
    restart: always
    container_name: app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/comfort
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"
    networks:
      - comfort-network
    depends_on:
      db:
        condition: service_healthy

  certbot:
    image: certbot/certbot
    depends_on:
      - nginx
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email pochta@gmail.com --agree-tos --no-eff-email --force-renewal -d doma-uyt.com.ua
  nginx:
    image: nginx:1.22.0-alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - web-root:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs   
    networks:
      - comfort-network
    links:
      - app
volumes:
  db-data:
  certbot-etc:
  certbot-var:
  web-root:
  dhparam:   # <======
    driver: local
    driver_opts:
      type: none
      device: /home/user/projects/idea/ComfortWeb/dhparam/
      o: bind

networks:
  comfort-network:
    driver: bridge

