INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (1, 'Матеріал оббивки шкірозамінник.', 'Кухоний кутовий диван', null, 'SOFA', 1);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (2, 'Матеріали: тканини, синтепон, флізелін, клей скоба.', 'Кутовий диван', 'від 4500 грн + матеріали', 'SOFA', 1);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (3, 'Матеріали: тканини, синтепон, флізелін, клей скоба.', 'Великий кутовий диван', 'від 6000 грн + матеріали', 'SOFA', 1);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (4, 'Перетяжка кутового п-образного дивана. Тканини шинил, у виробі зроблено заміну паралону, виконано ремонт столярні + заміна механізму трансформації. У вартість матеріалів увійде тканина при необхідності паралон, синтапон технічні тканини клей скоба при необхідності механізм трансформації.', 'Кутовий диван', '7500 грн + матеріали', 'SOFA', 1);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (5, 'Перетяжка кутового дивана, виконана в тканині рогожка', 'Кутовий диван', '5000 грн + матеріали', 'SOFA', 1);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (6, 'Кутовий диван виконаний у тканині антикіготь - флок.', 'Кутовий диван', '7000 грн + матеріали', 'SOFA', 1);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (7, 'Матеріали: тканини, синтепон, флізелін, клей скоба.', 'Диван + крісла', '5000 диван, 3000 кресло, + материалы', 'SOFA', 2);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (8, 'Перетяжка дивану + крісло. У цьому виробі тканини мікророгожка.', 'Диван', null, 'SOFA', 2);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (9, 'Матеріали: тканини, синтепон, флізелін, клей скоба.', 'Диван ', '4000 грн + материал', 'SOFA', 2);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (11, '
У цьому виробі тканина замша, з витратних матеріалів синтепон, флізелін, клей скоба.
', 'Диван', '4500 грн + матеріали', 'SOFA', 2);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (12, 'Перетяжка дивана + 2 крісла, робота диван 4000 грн., крісло одиниця 3000 + матеріали, тканини, синтепон, флізелін, клей скоба.', 'Диван', 'від 7000 грн + матеріали', 'SOFA', 2);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (13, 'Матеріали: тканини, синтепон, флізелін, клей скоба.', 'Диван', '4500 грн + матеріали', 'SOFA', 2);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (14, 'Диван перетяжка - Дніпро. У даному виробі зроблена заміна шкірозамінника на шкірозамінник середньої цінової категорії. Додатково синтепон клей скоба, заміна паралону ППУ на сидіннях.', 'Диван', '5000 грн + матеріали', 'SOFA', 2);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (15, 'Матеріали: тканини, синтепон, флізелін, клей скоба.', 'Диван', '4500 грн + матеріали.', 'SOFA', 2);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (16, 'Матеріали: тканини, синтепон, флізелін, клей скоба.', 'Диван + розкладне крісло', '5000 грн + матеріали', 'SOFA', 2);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (17, 'Перетяжка диван + 2 крісла, у Дніпрі, робота дивана 7000 грн, крісло одиниця - 3500 грн дане виробу є складним у роботі, за рахунок прошивки всього чохла на синтепоні, матеріали тканина, синтепон, клей скоба, флізелін. + кант для прошивки', 'Диван', 'від 10000 грн (диван + крісло)', 'SOFA', 2);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (18, 'Диван єврокнижка заміна тканини у Дніпрі. Даний виріб виконано в шкірозаміннику середньої цінової категорії, з матеріалів шкірозамінника, клей скоба, синтепон.', 'Диван', '4000 грн + матеріали', 'SOFA', 2);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (19, 'Перетяжка крісла в Дніпрі в італійський шкірозамінник, робота даного крісла 4500 + матеріали, ДАНИЙ ВИРОБ Вважається складним, так як чохол шиється повністю одні мцілим + прошитий на синтепоні.', 'Крісло', '4500 грн + матеріали', 'ARMCHAIR', 3);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (20, 'Перетяжка крісла, робота 2300 + матеріал. Матеріали: тканини, синтепон, флізелін, клей скоба.', 'Крісло', '2300 грн + матеріали', 'ARMCHAIR', 3);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (21, 'Перетяжка крісла зі зміною дизайну робота за один виріб 2750 + матеріали. Матеріали: тканини, синтепон, флізелін, клей скоба.', 'Крісло', '2750 грн + матеріали', 'ARMCHAIR', 3);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (22, 'Перетяжка крісла у Дніпрі, робота 2500 грн. Матеріали: тканини, синтепон, флізелін, клей скоба.', 'Крісло', '2500 грн + матеріали', 'ARMCHAIR', 3);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (23, 'Заміна тканини на кріслі у дніпрі, робота 2700 грн за одиницю. Матеріали: тканини, синтепон, флізелін, клей скоба.', 'Крісло', '2700 грн за одиницю + матеріали', 'ARMCHAIR', 3);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (24, 'Перетяжка крісла, Дніпро робота 3000 грн + матеріал', 'Крісло', '3000 грн + матеріали', 'ARMCHAIR', 3);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (25, 'Фасади верхній ряд МДФ фарбований.Нижній ряд ламіноване дсп Австрія в Пур поклейці. Фурнітура лінкенн систем. Ручка профільна чорного кольору для відкривання нижнього ряду. Стільниця пластик товщиною 28 мм.', 'Кухня', null, 'KITCHEN', 4);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (26, 'Виконана фасади МДФ фарбований з фрезеруванням. Ручка профільна чорного кольору. Стільниця кварц. Фурнітура Блюм. Фартух скло 6 мм із гартуванням. Корпус ДСП ламіноване 18мм.
', 'Кухня', null, 'KITCHEN', 4);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (27, 'Фасади Агт панелі. Стільниця + фартух кварц. Корпус виконаний з ламінованого дсп 18 мм. Фурнітура Блюм+ сервопривода Блюм. Ручка профільна чорного кольору. Підцвітка в кожному модулі спрацьовує на відкривання.', 'Вбудована кухня', null, 'KITCHEN', 4);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (28, 'Матеріал МДФ фарбований глянець.. Корпус ламіноване дсп 18 мм.. Стільниця пластик 38 мм.. Фурнітура Blum з доводчиками. В модуль мийка. Стійкість даного виробу 7400 цей виріб виконано за ескізом узгодженим нами із замовником.', 'Кухня blum', null, 'KITCHEN', 4);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (29, 'Фасади Савіолла (Віяр) з Пур поклейкою. Стільниця пластик Австрія. Центр стільниці в експозиції. Фурнітура Блюм. Даний виріб переходить до коридорної шафи. Виріб виконаний за погодженням нашого проекту із замовником.', 'Кухня', '110000 грн.', 'KITCHEN', 4);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (30, null, 'Кухня', null, 'KITCHEN', 4);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (31, null, 'Кухня', null, 'KITCHEN', 4);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (32, null, 'Кухня', null, 'KITCHEN', 4);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (33, null, 'Кухня', null, 'KITCHEN', 4);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (34, 'Шафа з розстібними фасадами. Фурнітура Блюм з доводчиками. Ручка торцева для відкривання фасадів. Фасади виконані з матеріалу МДФ фарбований в різній колірній тональності що надає виробу сучасного вигляду.', 'Шафа', null, 'CLOSET', 5);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (35, null, 'Шафа', null, 'CLOSET', 5);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (36, null, 'Шафа', null, 'CLOSET', 5);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (37, null, 'Шафа', null, 'CLOSET', 5);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (38, null, 'Шафа', null, 'CLOSET', 5);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (39, null, 'Шафа', null, 'CLOSET', 5);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (40, null, 'Шафа', null, 'CLOSET', 5);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (41, null, 'Шафа', null, 'CLOSET', 5);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (42, null, 'Шафа', null, 'CLOSET', 5);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (43, null, 'Шафа', null, 'CLOSET', 5);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (44, null, 'Шафа', null, 'CLOSET', 5);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (45, null, 'Шафа', null, 'CLOSET', 5);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (46, null, 'Дитяче ліжко та шафа', null, 'BED', 6);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (47, null, 'Дитяче ліжко та шафа', null, 'BED', 6);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (48, null, 'Меблі для ванної кімнати', null, null, 6);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (49, null, 'Підвісна полиця', null, null, 6);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (50, null, 'Стіл', null, 'TABLE', 6);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (51, null, 'Стіл у дитячу', null, 'TABLE', 6);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (52, null, 'Тумба для ванної кімнати', null, null, 6);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (53, null, 'Ліжко з вбудованими полицями', null, 'BED', 6);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (54, null, 'Тумба', null, null, 6);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (55, 'Дитячий куточок. 2 підвісних столи + пенал. Фурнітура Блюм. Матеріал ламіноване дсп виробництва кроношпан. Фасади МДФ фарбований мат. даний виріб виконано за ескізом замовника.', 'Дитячий куток', '29000 грн', 'TABLE', 6);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (56, null, 'Диван', null, 'SOFA', 7);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (57, null, 'Диван', null, 'SOFA', 7);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (58, null, 'Диван', null, 'SOFA', 7);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (59, null, 'Диван', null, 'SOFA', 7);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (60, null, 'Диван', null, 'SOFA', 7);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (61, null, 'Диван', null, 'SOFA', 7);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (62, null, 'Диван', null, 'SOFA', 7);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (63, null, 'Диван', null, 'SOFA', 7);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (64, null, 'Диван', null, 'SOFA', 7);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (65, null, 'Диван', null, 'SOFA', 7);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (66, null, 'Диван', null, 'SOFA', 7);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (67, null, 'Диван', null, 'SOFA', 7);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (68, null, 'Ліжко', null, 'BED', 8);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (69, null, 'Ліжко', null, 'BED', 8);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (70, null, 'Ліжко', null, 'BED', 8);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (71, null, 'Ліжко', null, 'BED', 8);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (72, null, 'Ліжко', null, 'BED', 8);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (73, null, 'Ліжко', null, 'BED', 8);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (74, null, 'Ліжко', null, 'BED', 8);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (75, null, 'Ліжко', null, 'BED', 8);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (76, null, 'Ліжко', null, 'BED', 8);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (77, null, 'Cтільці', null, 'CHAIR', 9);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (78, null, 'Крісло', null, 'ARMCHAIR', 9);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (79, null, 'Крісло', null, 'ARMCHAIR', 9);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (80, null, 'Пуфик', null, 'PUFF', 9);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (81, null, 'Стільці', null, 'CHAIR', 9);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (82, null, 'Стільці', null, 'CHAIR', 9);
INSERT INTO public.furniture (id, description, name, price, type, furniture_type_of_order_id) VALUES (83, 'Стінка в спальню. матеріал ламіноване дсп виробництва Австрія. полиці виконані в товщини 36 мм + фрезерування по лід підцвітку + рамкові фасади скла графіт. фурнітура Блюм під тип він - відкриття натисканням..конструкція виконана під геометрію стелі
', 'Стінка ', null, null, 6);
