INSERT INTO public.type_of_order (image, type) VALUES ( '/images/peretyazhka.png', 'Перетяжка меблів');
INSERT INTO public.type_of_order (image, type) VALUES ( '/images/korpusnaya.png', 'Корпусні меблі');
INSERT INTO public.type_of_order (image, type) VALUES ( '/images/na_zakaz.png', 'М''які меблі');


INSERT INTO public.furniture_type_of_order ( image, name, order_type_id) VALUES ( '/images/furniture_type_of_order/dyvany.jpg', 'Дивани під заказ', 3);
INSERT INTO public.furniture_type_of_order ( image, name, order_type_id) VALUES ( '/images/garderobny.png', 'Гардеробні', 2);
INSERT INTO public.furniture_type_of_order ( image, name, order_type_id) VALUES ( '/images/furniture_type_of_order/shafy.jpg', 'Шафи', 2);
INSERT INTO public.furniture_type_of_order ( image, name, order_type_id) VALUES ( '/images/furniture_type_of_order/dyvany.jpg', 'Звичайні дивани', 1);
INSERT INTO public.furniture_type_of_order ( image, name, order_type_id) VALUES ( '/images/furniture_type_of_order/kutovi.jpg', 'Кутові дивани', 1);
INSERT INTO public.furniture_type_of_order ( image, name, order_type_id) VALUES ( '/images/furniture_type_of_order/krisla.jpg', 'Крісла', 1);
INSERT INTO public.furniture_type_of_order ( image, name, order_type_id) VALUES ( '/images/furniture_type_of_order/stilzi.jpg', 'Стільці, пуфи та крісла', 3);
INSERT INTO public.furniture_type_of_order ( image, name, order_type_id) VALUES ( '/images/furniture_type_of_order/mebli_kimn.jpg', 'Меблі у різні кімнати', 2);
INSERT INTO public.furniture_type_of_order ( image, name, order_type_id) VALUES ( '/images/furniture_type_of_order/kuxni.jpg', 'Кухні', 2);
INSERT INTO public.furniture_type_of_order ( image, name, order_type_id) VALUES ( '/images/furniture_type_of_order/lizhka.jpg', 'Ліжка під заказ', 3);

INSERT INTO public.furniture ( description, name, price, priority, type, furniture_type_of_order_id) VALUES ( 'Матеріал оббивки шкірозамінник.', 'Кутовий диван', '5500 грн + матеріали', 'LOW', null, 5);
INSERT INTO public.furniture ( description, name, price, priority, type, furniture_type_of_order_id) VALUES ( 'Матеріали : шкірозамінник. Створена заміна ППУ, ремонт столярки.', 'Кутовий диван', '10000 грн + матеріали', 'HIGH', 'SOFA', 5);
INSERT INTO public.furniture ( description, name, price, priority, type, furniture_type_of_order_id) VALUES ( 'Заміна ткані на італійських диванах.', 'Великий кутовий диван', '5500 грн + матеріали', 'LOW', null, 5);
INSERT INTO public.furniture ( description, name, price, priority, type, furniture_type_of_order_id) VALUES ( 'Перетяжка кутового п-образного дивана. Тканини шинил, у виробі зроблено заміну паралону, виконано ремонт столярні + заміна механізму трансформації. У вартість матеріалів увійде тканина при необхідності паралон, синтапон технічні тканини клей скоба при необхідності механізм трансформації.', 'Кутовий диван', '7500 грн + матеріали', 'HIGH', 'SOFA', 5);
INSERT INTO public.furniture ( description, name, price, priority, type, furniture_type_of_order_id) VALUES ( 'Перетяжка кутового дивана, виконана в тканині рогожка', 'Кутовий диван', '5000 грн + матеріали', 'LOW', null, 5);
INSERT INTO public.furniture ( description, name, price, priority, type, furniture_type_of_order_id) VALUES ( 'Кутовий диван виконаний у тканині антикіготь - флок.', 'Кутовий диван', '7000 грн + матеріали', 'HIGH', 'SOFA', 5);
INSERT INTO public.furniture ( description, name, price, priority, type, furniture_type_of_order_id) VALUES ( 'Матеріали: тканини, синтепон, флізелін, клей скоба.', 'Диван + крісла', '5000 диван, 3000 кресло, + материалы', null, 'SOFA', 4);
INSERT INTO public.furniture ( description, name, price, priority, type, furniture_type_of_order_id) VALUES ( 'Перетяжка дивану + крісло. У цьому виробі тканини мікророгожка.', 'Диван', null, null, 'SOFA', 4);
INSERT INTO public.furniture ( description, name, price, priority, type, furniture_type_of_order_id) VALUES ( 'Матеріали: тканини, синтепон, флізелін, клей скоба.', 'Диван ', '4000 грн + материал', null, 'SOFA', 4);
INSERT INTO public.furniture ( description, name, price, priority, type, furniture_type_of_order_id) VALUES ( '
У цьому виробі тканина замша, з витратних матеріалів синтепон, флізелін, клей скоба.
', 'Диван', '4500 грн + матеріали', 'LOW', 'SOFA', 4);
INSERT INTO public.furniture ( description, name, price, priority, type, furniture_type_of_order_id) VALUES ( 'Перетяжка дивана + 2 крісла, робота диван 4000 грн., крісло одиниця 3000 + матеріали, тканини, синтепон, флізелін, клей скоба.', 'Диван', 'від 7000 грн + матеріали', 'LOW', 'SOFA', 4);
INSERT INTO public.furniture ( description, name, price, priority, type, furniture_type_of_order_id) VALUES ( 'Матеріали: тканини, синтепон, флізелін, клей скоба.', 'Диван', '4500 грн + матеріали', 'HIGH', 'SOFA', 4);
INSERT INTO public.furniture ( description, name, price, priority, type, furniture_type_of_order_id) VALUES ( 'Диван перетяжка - Дніпро. У даному виробі зроблена заміна шкірозамінника на шкірозамінник середньої цінової категорії. Додатково синтепон клей скоба, заміна паралону ППУ на сидіннях.', 'Диван', '5000 грн + матеріали', 'HIGH', 'SOFA', 4);
INSERT INTO public.furniture ( description, name, price, priority, type, furniture_type_of_order_id) VALUES ( 'Матеріали: тканини, синтепон, флізелін, клей скоба.', 'Диван', '4500 грн + матеріали.', 'LOW', 'SOFA', 4);
INSERT INTO public.furniture ( description, name, price, priority, type, furniture_type_of_order_id) VALUES ( 'Матеріали: тканини, синтепон, флізелін, клей скоба.', 'Диван + розкладне крісло', '5000 грн + матеріали', 'HIGH', 'SOFA', 4);
INSERT INTO public.furniture ( description, name, price, priority, type, furniture_type_of_order_id) VALUES ( 'Перетяжка диван + 2 крісла, у Дніпрі, робота дивана 7000 грн, крісло одиниця - 3500 грн дане виробу є складним у роботі, за рахунок прошивки всього чохла на синтепоні, матеріали тканина, синтепон, клей скоба, флізелін. + кант для прошивки', 'Диван', 'від 10000 грн (диван + крісло)', 'HIGH', 'SOFA', 4);
INSERT INTO public.furniture ( description, name, price, priority, type, furniture_type_of_order_id) VALUES ( 'Диван єврокнижка заміна тканини у Дніпрі. Даний виріб виконано в шкірозаміннику середньої цінової категорії, з матеріалів шкірозамінника, клей скоба, синтепон.', 'Диван', '4000 грн + матеріали', null, 'SOFA', 4);
INSERT INTO public.furniture ( description, name, price, priority, type, furniture_type_of_order_id) VALUES ( 'Перетяжка крісла в Дніпрі в італійський шкірозамінник, робота даного крісла 4500 + матеріали, ДАНИЙ ВИРОБ Вважається складним, так як чохол шиється повністю одні мцілим + прошитий на синтепоні.', 'Крісло', '4500 грн + матеріали', null, 'ARMCHAIR', 6);
INSERT INTO public.furniture ( description, name, price, priority, type, furniture_type_of_order_id) VALUES ( 'Перетяжка крісла, робота 2300 + матеріал. Матеріали: тканини, синтепон, флізелін, клей скоба.', 'Крісло', '2300 грн + матеріали', null, 'ARMCHAIR', 6);
INSERT INTO public.furniture ( description, name, price, priority, type, furniture_type_of_order_id) VALUES ( 'Перетяжка крісла зі зміною дизайну робота за один виріб 2750 + матеріали. Матеріали: тканини, синтепон, флізелін, клей скоба.', 'Крісло', '2750 грн + матеріали', null, 'ARMCHAIR', 6);
INSERT INTO public.furniture ( description, name, price, priority, type, furniture_type_of_order_id) VALUES ( 'Перетяжка крісла у Дніпрі, робота 2500 грн. Матеріали: тканини, синтепон, флізелін, клей скоба.', 'Крісло', '2500 грн + матеріали', 'HIGH', 'ARMCHAIR', 6);
INSERT INTO public.furniture ( description, name, price, priority, type, furniture_type_of_order_id) VALUES ( 'Заміна тканини на кріслі у дніпрі, робота 2700 грн за одиницю. Матеріали: тканини, синтепон, флізелін, клей скоба.', 'Крісло', '2700 грн за одиницю + матеріали', 'HIGH', 'ARMCHAIR', 6);
INSERT INTO public.furniture ( description, name, price, priority, type, furniture_type_of_order_id) VALUES ( 'Перетяжка крісла, Дніпро робота 3000 грн + матеріал', 'Крісло', '3000 грн + матеріали', 'HIGH', 'ARMCHAIR', 6);
INSERT INTO public.furniture ( description, name, price, priority, type, furniture_type_of_order_id) VALUES ( 'Фасади верхній ряд МДФ фарбований.Нижній ряд ламіноване дсп Австрія в Пур поклейці. Фурнітура лінкенн систем. Ручка профільна чорного кольору для відкривання нижнього ряду. Стільниця пластик товщиною 28 мм.', 'Кухня', null, null, 'KITCHEN', 9);
INSERT INTO public.furniture ( description, name, price, priority, type, furniture_type_of_order_id) VALUES ( 'Виконана фасади МДФ фарбований з фрезеруванням. Ручка профільна чорного кольору. Стільниця кварц. Фурнітура Блюм. Фартух скло 6 мм із гартуванням. Корпус ДСП ламіноване 18мм.
', 'Кухня', null, null, 'KITCHEN', 9);
INSERT INTO public.furniture ( description, name, price, priority, type, furniture_type_of_order_id) VALUES ( 'Фасади Агт панелі. Стільниця + фартух кварц. Корпус виконаний з ламінованого дсп 18 мм. Фурнітура Блюм+ сервопривода Блюм. Ручка профільна чорного кольору. Підцвітка в кожному модулі спрацьовує на відкривання.', 'Вбудована кухня', null, null, 'KITCHEN', 9);
INSERT INTO public.furniture ( description, name, price, priority, type, furniture_type_of_order_id) VALUES ( 'Матеріал МДФ фарбований глянець.. Корпус ламіноване дсп 18 мм.. Стільниця пластик 38 мм.. Фурнітура Blum з доводчиками. В модуль мийка. Стійкість даного виробу 7400 цей виріб виконано за ескізом узгодженим нами із замовником.', 'Кухня blum', null, null, 'KITCHEN', 9);
INSERT INTO public.furniture ( description, name, price, priority, type, furniture_type_of_order_id) VALUES ( 'Фасади Савіолла (Віяр) з Пур поклейкою. Стільниця пластик Австрія. Центр стільниці в експозиції. Фурнітура Блюм. Даний виріб переходить до коридорної шафи. Виріб виконаний за погодженням нашого проекту із замовником.', 'Кухня', '110000 грн.', null, 'KITCHEN', 9);
INSERT INTO public.furniture ( description, name, price, priority, type, furniture_type_of_order_id) VALUES ( null, 'Кухня', null, null, 'KITCHEN', 9);
INSERT INTO public.furniture ( description, name, price, priority, type, furniture_type_of_order_id) VALUES ( null, 'Кухня', null, null, 'KITCHEN', 9);
INSERT INTO public.furniture ( description, name, price, priority, type, furniture_type_of_order_id) VALUES ( null, 'Кухня', null, null, 'KITCHEN', 9);
INSERT INTO public.furniture ( description, name, price, priority, type, furniture_type_of_order_id) VALUES ( 'Шафа з розстібними фасадами. Фурнітура Блюм з доводчиками. Ручка торцева для відкривання фасадів. Фасади виконані з матеріалу МДФ фарбований в різній колірній тональності що надає виробу сучасного вигляду.', 'Шафа', null, null, 'CLOSET', 3);
INSERT INTO public.furniture ( description, name, price, priority, type, furniture_type_of_order_id) VALUES ( null, 'Шафа', null, null, 'CLOSET', 3);
INSERT INTO public.furniture ( description, name, price, priority, type, furniture_type_of_order_id) VALUES ( null, 'Шафа', null, null, 'CLOSET', 3);
INSERT INTO public.furniture ( description, name, price, priority, type, furniture_type_of_order_id) VALUES ( null, 'Шафа', null, null, 'CLOSET', 3);
INSERT INTO public.furniture ( description, name, price, priority, type, furniture_type_of_order_id) VALUES ( null, 'Шафа', null, null, 'CLOSET', 3);
INSERT INTO public.furniture ( description, name, price, priority, type, furniture_type_of_order_id) VALUES ( null, 'Шафа', null, null, 'CLOSET', 3);
INSERT INTO public.furniture ( description, name, price, priority, type, furniture_type_of_order_id) VALUES ( null, 'Шафа', null, null, 'CLOSET', 3);
INSERT INTO public.furniture ( description, name, price, priority, type, furniture_type_of_order_id) VALUES ( null, 'Шафа', null, null, 'CLOSET', 3);
INSERT INTO public.furniture ( description, name, price, priority, type, furniture_type_of_order_id) VALUES ( null, 'Шафа', null, null, 'CLOSET', 3);
INSERT INTO public.furniture ( description, name, price, priority, type, furniture_type_of_order_id) VALUES ( null, 'Шафа', null, null, 'CLOSET', 3);
INSERT INTO public.furniture ( description, name, price, priority, type, furniture_type_of_order_id) VALUES ( null, 'Шафа', null, null, 'CLOSET', 3);
INSERT INTO public.furniture ( description, name, price, priority, type, furniture_type_of_order_id) VALUES ( null, 'Шафа', null, null, 'CLOSET', 3);
INSERT INTO public.furniture ( description, name, price, priority, type, furniture_type_of_order_id) VALUES ( null, 'Дитяче ліжко та шафа', null, null, 'BED', 8);
INSERT INTO public.furniture ( description, name, price, priority, type, furniture_type_of_order_id) VALUES ( null, 'Дитяче ліжко та шафа', null, null, 'BED', 8);
INSERT INTO public.furniture ( description, name, price, priority, type, furniture_type_of_order_id) VALUES ( null, 'Меблі для ванної кімнати', null, null, null, 8);
INSERT INTO public.furniture ( description, name, price, priority, type, furniture_type_of_order_id) VALUES ( null, 'Підвісна полиця', null, null, null, 8);
INSERT INTO public.furniture ( description, name, price, priority, type, furniture_type_of_order_id) VALUES ( null, 'Стіл', null, null, 'TABLE', 8);
INSERT INTO public.furniture ( description, name, price, priority, type, furniture_type_of_order_id) VALUES ( null, 'Стіл у дитячу', null, null, 'TABLE', 8);
INSERT INTO public.furniture ( description, name, price, priority, type, furniture_type_of_order_id) VALUES ( null, 'Тумба для ванної кімнати', null, null, null, 8);
INSERT INTO public.furniture ( description, name, price, priority, type, furniture_type_of_order_id) VALUES ( null, 'Тумба', null, null, null, 8);
INSERT INTO public.furniture ( description, name, price, priority, type, furniture_type_of_order_id) VALUES ( 'Дитячий куточок. 2 підвісних столи + пенал. Фурнітура Блюм. Матеріал ламіноване дсп виробництва кроношпан. Фасади МДФ фарбований мат. даний виріб виконано за ескізом замовника.', 'Дитячий куток', '29000 грн', null, 'TABLE', 8);
INSERT INTO public.furniture ( description, name, price, priority, type, furniture_type_of_order_id) VALUES ( '', 'Диван', '', 'HIGH', null, 1);
INSERT INTO public.furniture ( description, name, price, priority, type, furniture_type_of_order_id) VALUES ( null, 'Диван', null, null, 'SOFA', 1);
INSERT INTO public.furniture ( description, name, price, priority, type, furniture_type_of_order_id) VALUES ( null, 'Диван', null, null, 'SOFA', 1);
INSERT INTO public.furniture ( description, name, price, priority, type, furniture_type_of_order_id) VALUES ( null, 'Диван', null, null, 'SOFA', 1);
INSERT INTO public.furniture ( description, name, price, priority, type, furniture_type_of_order_id) VALUES ( null, 'Диван', null, null, 'SOFA', 1);
INSERT INTO public.furniture ( description, name, price, priority, type, furniture_type_of_order_id) VALUES ( null, 'Диван', null, null, 'SOFA', 1);
INSERT INTO public.furniture ( description, name, price, priority, type, furniture_type_of_order_id) VALUES ( null, 'Диван', null, null, 'SOFA', 1);
INSERT INTO public.furniture ( description, name, price, priority, type, furniture_type_of_order_id) VALUES ( null, 'Диван', null, null, 'SOFA', 1);
INSERT INTO public.furniture ( description, name, price, priority, type, furniture_type_of_order_id) VALUES ( null, 'Диван', null, null, 'SOFA', 1);
INSERT INTO public.furniture ( description, name, price, priority, type, furniture_type_of_order_id) VALUES ( null, 'Диван', null, null, 'SOFA', 1);
INSERT INTO public.furniture ( description, name, price, priority, type, furniture_type_of_order_id) VALUES ( null, 'Диван', null, null, 'SOFA', 1);
INSERT INTO public.furniture ( description, name, price, priority, type, furniture_type_of_order_id) VALUES ( null, 'Диван', null, null, 'SOFA', 1);
INSERT INTO public.furniture ( description, name, price, priority, type, furniture_type_of_order_id) VALUES ( null, 'Ліжко', null, null, 'BED', 10);
INSERT INTO public.furniture ( description, name, price, priority, type, furniture_type_of_order_id) VALUES ( null, 'Ліжко', null, null, 'BED', 10);
INSERT INTO public.furniture ( description, name, price, priority, type, furniture_type_of_order_id) VALUES ( null, 'Ліжко', null, null, 'BED', 10);
INSERT INTO public.furniture ( description, name, price, priority, type, furniture_type_of_order_id) VALUES ( null, 'Ліжко', null, null, 'BED', 10);
INSERT INTO public.furniture ( description, name, price, priority, type, furniture_type_of_order_id) VALUES ( null, 'Ліжко', null, null, 'BED', 10);
INSERT INTO public.furniture ( description, name, price, priority, type, furniture_type_of_order_id) VALUES ( null, 'Ліжко', null, null, 'BED', 10);
INSERT INTO public.furniture ( description, name, price, priority, type, furniture_type_of_order_id) VALUES ( null, 'Ліжко', null, null, 'BED', 10);
INSERT INTO public.furniture ( description, name, price, priority, type, furniture_type_of_order_id) VALUES ( null, 'Ліжко', null, null, 'BED', 10);
INSERT INTO public.furniture ( description, name, price, priority, type, furniture_type_of_order_id) VALUES ( '', 'Крісло', '', 'HIGH', 'ARMCHAIR', 7);
INSERT INTO public.furniture ( description, name, price, priority, type, furniture_type_of_order_id) VALUES ( null, 'Крісло', null, null, 'ARMCHAIR', 7);
INSERT INTO public.furniture ( description, name, price, priority, type, furniture_type_of_order_id) VALUES ( null, 'Крісло', null, null, 'ARMCHAIR', 7);
INSERT INTO public.furniture ( description, name, price, priority, type, furniture_type_of_order_id) VALUES ( null, 'Пуфик', null, null, 'PUFF', 7);
INSERT INTO public.furniture ( description, name, price, priority, type, furniture_type_of_order_id) VALUES ( null, 'Стільці', null, null, 'CHAIR', 7);
INSERT INTO public.furniture ( description, name, price, priority, type, furniture_type_of_order_id) VALUES ( '', 'Крісло', '', 'HIGH', 'ARMCHAIR', 7);
INSERT INTO public.furniture ( description, name, price, priority, type, furniture_type_of_order_id) VALUES ( 'Стінка в спальню. матеріал ламіноване дсп виробництва Австрія. полиці виконані в товщини 36 мм + фрезерування по лід підцвітку + рамкові фасади скла графіт. фурнітура Блюм під тип він - відкриття натисканням..конструкція виконана під геометрію стелі
', 'Стінка ', null, null, null, 8);
